# Generated by Django 3.1.5 on 2021-02-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links_saver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('groupId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useful_links_saver.grouplinks')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
