# Generated by Django 3.1.6 on 2021-02-04 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links_saver', '0002_auto_20210202_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
