# Generated by Django 3.1.6 on 2021-02-04 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links_saver', '0003_auto_20210204_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplinks',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
